server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  #配置静态路径，多个可用逗号隔开
  resources:
    static-locations: file:${img.location}
  mvc:
    static-path-pattern: /**
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF8&&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# redis配置
  redis:
    #数据库索引，默认为0
    database: 0
    #服务器地址
    host: localhost
    #端口
    port: 6379
    #密码（默认为空）
    password:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
#文件基础路径
img:
  location: E:/blog/file
#======================================
#    分布式文件存储设置
#======================================
fdfs:
  so-timeout: 1500
  connect-timeout: 500
  thumbImage:
    width: 150
    height: 150
  tracker-list:
    - 192.168.18.129:22122
  web-server-url: http://192.168.18.128/